apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dzw2pzcnr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dzw2pzcnr-go 
  name: dzw2pzcnr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dzw2pzcnr-go 
